backend:
  name: github
  repo: jandelmar/brnogo.cz
  branch: gatsby-netlify-cms
# Media files will be stored in the repo under static/images/uploads
media_folder: static/images/uploads
 # The src attribute for uploaded media will begin with /images/uploads
public_folder: /images/uploads
collections:
  - name: jidlo
    label: Jídlo
    create: true
    folder: content/jidlo/
    identifier_field: cz-jidlo
    format: yml
    fields:
      - { name: jidlo, label: Jídlo, widget: string }
      - { name: popis, label: Popis, widget: string }
      - label: EN
        name: en
        widget: object
        fields:
          - { name: en-jidlo, label: Jídlo, widget: string }
          - { name: en-popis, label: Popis, widget: string }
      - { name: kategorie, label: Kategorie, widget: relation, collection: jidlo-kategorie, searchFields: [kategorie], valueField: kategorie }
      - { name: alergeny, label: Alergeny, widget: list, required: false }
      - { name: typ, label: Typ, widget: select, options: [V, VEG], required: false }
      - { name: cena, label: Cena, widget: number, valueType: int }
  - name: jidlo-kategorie
    label: Kategorie jídel
    create: true
    folder: content/jidlo-kategorie/
    identifier_field: cz-jidlo
    format: yml
    fields:
      - { name: kategorie, label: Kategorie, widget: string }
      - label: EN
        name: en
        widget: object
        fields:
          - { name: en-kategorie, label: Kategorie, widget: string }