backend:
  name: github
  repo: jandelmar/brnogo.cz
  branch: netlify-cms-test
# Media files will be stored in the repo under static/images/uploads
media_folder: "static/images/uploads"
 # The src attribute for uploaded media will begin with /images/uploads
public_folder: "/images/uploads"
collections:
  - name: jidlo
    label: Jídlo
    create: true
    folder: "content/jidlo/"
    format: "yml"
    fields:
      - {label: "CZ kategorie", name: "kategorie", widget: "string"}
      - {label: "CZ jidlo", name: "jidlo", widget: "string"}
      - {label: "CZ popis", name: "popis", widget: "string"}
  - name: napoje
    label: Nápoje
    create: true
    folder: "content/napoje/"
    format: "yml"
    fields:
      - {label: "CZ kategorie", name: "kategorie", widget: "string"}
      - {label: "CZ napoj", name: "napoj", widget: "string"}
