backend:
  # name: test-repo
  name: github
  repo: jandelmar/brnogo.cz
  branch: gatsby-netlify-cms
# Media files will be stored in the repo under static/images/uploads
media_folder: static/images/uploads
 # The src attribute for uploaded media will begin with /images/uploads
public_folder: /images/uploads
collections:
  - name: jidlo
    label: Jídlo
    create: true
    folder: content/jidlo/
    identifier_field: jidlo
    format: yml
    fields:
      - { name: poradi, label: Pořadí, widget: number, default: 1, min: 1 }      
      - { name: kategorie, label: Kategorie, widget: relation, collection: jidlo-kategorie, searchFields: [kategorie], valueField: kategorie }
      - { name: jidlo, label: Jídlo, widget: string }
      - { name: popis, label: Popis, widget: string }
      - label: EN
        name: en
        widget: object
        fields:
          - { name: en_kategorie, label: Kategorie, widget: relation, collection: jidlo-kategorie, searchFields: [en_kategorie], valueField: en_kategorie }
          - { name: en_jidlo, label: Jídlo, widget: string }
          - { name: en_popis, label: Popis, widget: string }
      - { name: alergeny, label: Alergeny, widget: list, required: false }
      - { name: typ, label: Typ, widget: select, options: [V, VEG, BL], required: false }
      - { name: cena, label: Cena, widget: number, valueType: int, default: 1, min: 1 }
  - name: jidlo-kategorie
    label: Kategorie jidlo
    create: true
    folder: content/jidlo-kategorie/
    identifier_field: kategorie
    format: yml
    fields:
      - { name: poradi, label: Pořadí, widget: number, default: 1, min: 1 }
      - { name: kategorie, label: Kategorie, widget: string }
      - { name: info, label: Info, widget: string, required: false }
      - name: en
        label: EN
        widget: object
        fields:
          - { name: en_kategorie, label: Kategorie, widget: string }
          - { name: en_info, label: Info, widget: string, required: false }
  - name: ostatni
    label: Ostatní
    files:
      - name: o-nas
        label: O nás
        file: content/o-nas.yml
        fields:
          - { name: oteviraci_doba, label: Otevírací doba, widget: list}
          - { name: telefon, label: Telefon, widget: string}
          - { name: email, label: Email, widget: string}
          - { name: adresa, label: Adresa, widget: string}
          - { name: adresa_mapa, label: Adresa mapa, widget: string}
          - { name: provozovatel, label: Provozovatel, widget: list}
          - name: en
            label: EN
            widget: object
            fields:
              - { name: en_oteviraci_doba, label: Otevírací doba, widget: list}
              - { name: en_telefon, label: Telefon, widget: string}
              - { name: en_email, label: Email, widget: string}
              - { name: en_adresa, label: Adresa, widget: string}
              - { name: en_adresa_mapa, label: Adresa mapa, widget: string}
              - { name: en_provozovatel, label: Provozovatel, widget: list}
      - name: menu-info
        label: Menu info
        file: content/menu-info.yml
        fields:
          - { name: krabice, label: Krabice, widget: string}
          - { name: druhy_jidel, label: Druhy jídel, widget: string}
          - { name: alergeny, label: Alergeny, widget: list}
