backend:
  name: github
  repo: jandelmar/brnogo.cz
  branch: netlify-cms-test
# Media files will be stored in the repo under static/images/uploads
media_folder: static/images/uploads
 # The src attribute for uploaded media will begin with /images/uploads
public_folder: /images/uploads
collections:
  - name: jidlo
    label: Jídlo
    create: true
    folder: content/jidlo/
    identifier_field: cz-jidlo
    format: yml
    fields:
      - { name: cz-kategorie, label: CZ kategorie, widget: string }
      - { name: cz-jidlo, label: CZ jidlo, widget: string }
      - { name: cz-popis, label: CZ popis, widget: string }
      - { name: en-kategorie, label: EN kategorie, widget: string }
      - { name: en-jidlo, label: EN jidlo, widget: string }
      - { name: en-popis, label: EN popis, widget: string }
